version: '2'

services:

  springboot.mybatis.mysql:
    container_name: springboot.mybatis.mysql
    hostname: smm
    image: mysql:5.6
    environment:
      - HOSTNAME=mysql
      - MYSQL_ROOT_PASSWORD=123456
    working_dir: /home/smm
    # MySQL 在容器启动时会自动执行 /usr/local/bin/docker-entrypoint.sh 该脚本, 并自动执行 /docker-entrypoint-initdb.d 目录下的脚本
#    command: /bin/bash -c './script.sh;'
    volumes:
      - ./data/mysql/datadir:/usr/data
      - ./data/mysql/conf:/etc/mysql
      - ./data/mysql/smm:/home/smm
      - ./auto-script:/docker-entrypoint-initdb.d
    ports:
      - 3301:3306
    logging:
      driver: "json-file"
      options:
        max-size: "200M"
        max-file: "5"


  springboot.mybatis.web:
    container_name: springboot.mybatis.web
    hostname: smw
    image: springboot-mybatis-web:latest
    environment: 
      - MYSQL_IP=119.23.XXX.XXX
      - MYSQL_PORT=3301
      - MYSQL_DB=answer
      - MYSQL_UNAME=docker
      - MYSQL_PASSWD=123456
    working_dir: /home/smw
    volumes:
      - ./data/web/smw:/home/smw
    ports:
      - 8081:8888
    depends_on:
      - springboot.mybatis.mysql
    logging:
      driver: "json-file"
      options:
        max-size: "200M"
        max-file: "5"
